spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8181
  servlet:
    context-path: /uaa

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG